version: 2
jobs:
  build:
    working_directory: ~/circleci-heroku
    docker:
      - image: circleci/node:9.3
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
  deploy:
    environment:
      - HEROKU_APP: still-spire-56767
    working_directory: ~/circleci-heroku
    machine: true
    steps:
      - checkout
      - run:
          name: setup Heroku
          command: bash .circleci/setup-heroku.sh
      - run:
          name: Deploy Master to Heroku
          command: |
              heroku git:remote -a $HEROKU_APP
              git push --force git@heroku.com:$HEROKU_APP HEAD:refs/heads/master