version: 2
jobs:
  build:
    working_directory: ~/circleci-heroku
    docker:
      - image: circleci/node:9.3
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install npm@latest'
      # - restore_cache:
      #     key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      # - save_cache:
      #     key: dependency-cache-{{ checksum "package.json" }}
      #     paths:
      #       - ./node_modules
  deploy:
    environment:
      - HEROKU_APP: still-spire-56767
    working_directory: ~/circleci-heroku
    machine: true
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "cc:40:d1:99:63:e0:1f:cb:6f:0c:32:7b:be:22:2c:87"
      - run:
          name: setup Heroku
          command: bash .circleci/setup-heroku.sh
      - run:
          name: Deploy Master to Heroku
          command: |
              heroku git:remote -a $HEROKU_APP
              git push --force git@heroku.com:$HEROKU_APP HEAD:refs/heads/master
              # git push --force https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP.git HEAD:refs/heads/master
              sleep 5
              heroku restart

workflows:
    version: 2
    build-deploy:
        jobs:
            - build
            - deploy:
                requires:
                    - build